#!/bin/sh

mount -t devtmpfs devtmpfs /dev
mount -t proc proc /proc
mount -t sysfs sysfs /sys

mkdir -p /tmp /run
mount -t tmpfs tmpfs /tmp
mount -t tmpfs tmpfs /run

# force controlling tty on serial console
exec setsid sh -c 'exec </dev/ttyS0 >/dev/ttyS0 2>&1 /bin/sh'
